from django.conf.urls import patterns, url
from admin import views
from django.conf.urls.defaults import * 

urlpatterns = patterns('', 
	url(r'^$', views.index, name='index'), 
	url(r'^super/$', views.super_interface, name='super_interface'), 
	url(r'^super/insert/$', views.insert_system_admin, name='insert_system_admin'), 
	url(r'^super/select/$', views.select_system_admin, name='select_system_admin'), 
	url(r'^super/(?P<username>\w+)/edit/$', views.edit_system_admin, name='edit_system_admin'), 
	url(r'^super/(?P<username>\w+)/detail/$', views.detail_system_admin, name='detail_system_admin'),
	url(r'^super/(?P<username>\w+)/delete/$', views.delete_system_admin, name='delete_system_admin'), 
	url(r'^super/(?P<username>\w+)/update/$', views.update_system_admin, name='update_system_admin'), 
	url(r'^system/$', views.system_interface, name='system_interface'), 
	url(r'^system/user/$', views.user_manage, name='user_manage'), 
	url(r'^system/user/insert/$', views.insert_user, name='insert_user'), 
	url(r'^system/user/select/$', views.select_user, name='select_user'), 
	url(r'^system/user/(?P<username>\w+)/edit/$', views.edit_user, name='edit_user'), 
	url(r'^system/user/(?P<username>\w+)/detail/$', views.detail_user, name='detail_user'), 
	url(r'^system/user/(?P<username>\w+)/delete/$', views.delete_user, name='delete_user'), 
	url(r'^system/user/(?P<username>\w+)/update/$', views.update_user, name='update_user'), 
	url(r'^system/other/$', views.other_admin, name='other_admin'), 
	url(r'^system/other/insert/$', views.insert_other_admin, name='insert_other_admin'), 
	url(r'^system/other/select/$', views.select_other_admin, name='select_other_admin'), 
	url(r'^system/other/(?P<username>\w+)/edit/$', views.edit_other_admin, name='edit_other_admin'), 
	url(r'^system/other/(?P<username>\w+)/detail/$', views.detail_other_admin, name='detail_other_admin'), 
	url(r'^system/other/(?P<username>\w+)/delete/$', views.delete_other_admin, name='delete_other_admin'), 
	url(r'^system/other/(?P<username>\w+)/update/$', views.update_other_admin, name='update_other_admin'), 
	url(r'^system/dispute/$', views.dispute_manage, name='dispute_manage'), 
	url(r'^system/dispute/select/$', views.select_dispute, name='dispute_select'), 
	url(r'^system/dispute/(?P<dispute_id>\d+)/result', views.result_dispute, name='result_dispute'), 
	url(r'^system/verification/$', views.verification, name='verification'), 
	url(r'^system/verification/(?P<username>\w+)/verify', views.verify, name='verify'), 
	#url(r'^some/', include(admin.site.urls)),
)